const $=selector=>document.querySelector(selector),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=value=>Number(value).toLocaleString('pt-BR',{minimumFractionDigits:2,maximumFractionDigits:2});let cache={subjects:[],students:[],scores:[]},scoreMode='subject',pdfImportStudentId='';
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}}),data=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(data.error||'Não foi possível concluir a operação.');error.logs=Array.isArray(data.logs)?data.logs:[];error.userAction=data.user_action||'';throw error}return data}
function closeAdminFeedback(){const dialog=$('#admin-feedback-dialog');if(!dialog)return;if(typeof dialog.close==='function')dialog.close();else dialog.removeAttribute('open')}
function showAdminFeedback({title='Aviso',eyebrow='Aviso',message='',userAction='',logs=[],tone='info'}={}){const dialog=$('#admin-feedback-dialog'),content=$('#admin-feedback-content');if(!dialog||!content){window.alert([message,userAction].filter(Boolean).join('\n\n'));return}$('#admin-feedback-eyebrow').textContent=eyebrow;$('#admin-feedback-title').textContent=title;const logItems=(logs||[]).map(item=>{const level=String(item.level||'info').toLowerCase();return`<li class="log-${esc(level)}"><span class="log-level">${esc(level)}</span><div><div>${esc(item.message||'')}</div>${item.at?`<div class="log-meta">${esc(item.at)}</div>`:''}</div></li>`}).join('');content.innerHTML=`${message?`<p>${esc(message)}</p>`:''}${userAction?`<div class="admin-feedback-action"><strong>O que você deve fazer</strong><span>${esc(userAction)}</span></div>`:''}${logItems?`<p><strong>Detalhes para ajuste</strong></p><ul class="admin-feedback-logs">${logItems}</ul>`:''}`;dialog.dataset.tone=tone;if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','')}
$('#admin-feedback-close')?.addEventListener('click',closeAdminFeedback);$('#admin-feedback-close-bottom')?.addEventListener('click',closeAdminFeedback);$('#admin-feedback-dialog')?.addEventListener('click',event=>{if(event.target===$('#admin-feedback-dialog'))closeAdminFeedback()});
function dashboard(user){$('#login-panel').hidden=true;$('#dashboard').hidden=false;$('#initial-warning').hidden=!user.must_change_password;loadData()}
async function check(){try{dashboard(await api('/api/admin/session'))}catch{$('#login-panel').hidden=false;$('#dashboard').hidden=true}}
$('#admin-login-form').addEventListener('submit',async e=>{e.preventDefault();try{dashboard(await api('/api/admin/login',{method:'POST',body:JSON.stringify({username:$('#admin-user').value.trim(),password:$('#admin-password').value})}))}catch(error){$('#login-message').textContent=error.message}});
function bindForm(selector,path,success,preserve=[]){$(selector).addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,message=form.querySelector('.panel-message'),names=typeof preserve==='function'?preserve():preserve,kept=Object.fromEntries(names.map(name=>[name,form.elements[name]?.value||'']));try{await api(path,{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});message.textContent=success;form.reset();await loadData();for(const[name,value]of Object.entries(kept))if(form.elements[name])form.elements[name].value=value;if(selector==='#score-form'){updateRule();updateObservation();$(scoreMode==='student'?'#score-subject':'#score-student').focus()}}catch(error){message.textContent=error.message}})}
bindForm('#student-form','/api/admin/student','Discente salvo com sucesso.');bindForm('#score-form','/api/admin/score','Notas salvas com sucesso.',()=>scoreMode==='student'?['student_id']:['subject_id']);bindForm('#exam-form','/api/admin/exams','Data cadastrada no calendário.');
$('#password-form').addEventListener('submit',async e=>{e.preventDefault();const message=e.currentTarget.querySelector('.panel-message');try{await api('/api/admin/password',{method:'POST',body:JSON.stringify({password:$('#new-password').value})});message.textContent='Senha alterada.';$('#initial-warning').hidden=true;e.currentTarget.reset()}catch(error){message.textContent=error.message}});
function updateRule(){const subject=cache.subjects.find(x=>String(x.id)===$('#score-subject').value);if(!subject)return;const apt=subject.grading_mode==='apt',taf=subject.grading_mode==='taf',two=subject.exam_count===2;const exam1=$('#score-form [name=exam1]'),exam2=$('#score-form [name=exam2]'),work=$('#score-form [name=work]'),status=$('#score-form [name=status]');$('#status-label').hidden=!apt;$('.score-fields').hidden=apt;status.disabled=!apt;if(!apt)status.value='';if(apt){for(const input of [exam1,exam2,work]){input.value='';input.disabled=true}$('#score-rule').textContent='Resultado qualitativo: selecione Apto ou Inapto. Esta disciplina não integra a pontuação do ranking.';return}exam1.disabled=!taf&&!two;exam2.disabled=false;work.disabled=false;if(exam1.disabled)exam1.value='';$('#exam1-label .field-name').textContent=taf?'1º TAF':'Avaliação Complementar (AVC)';$('#exam2-label .field-name').textContent=taf?'2º TAF':'Avaliação Final (AVF)';$('#work-label .field-name').textContent=taf?'3º TAF':'Trabalho';$('#exam1-max').textContent='(máx. 3)';$('#exam2-max').textContent=`(máx. ${taf?3:two?4:7})`;$('#work-max').textContent=`(máx. ${taf?4:3})`;exam1.max=3;exam2.max=taf?3:two?4:7;work.max=taf?4:3;$('#exam1-label').hidden=!taf&&!two;$('#exam2-label').hidden=false;$('#score-rule').textContent=taf?'Educação Física: 1º TAF 3 pontos • 2º TAF 3 pontos • 3º TAF 4 pontos':two?'AVC: 3 pontos • AVF: 4 pontos • Trabalho: 3 pontos':'AVF: 7 pontos • Trabalho: 3 pontos'}
function updateCalendarTypes(){const subject=cache.subjects.find(x=>x.name===$('#calendar-subject').value);if(!subject)return;const types=subject.grading_mode==='apt'?['Resultado Apto/Inapto']:subject.grading_mode==='taf'?['1º TAF','2º TAF','3º TAF']:subject.exam_count===1?['Avaliação Final (AVF)','Trabalho']:['Avaliação Complementar (AVC)','Avaliação Final (AVF)','Trabalho'];$('#calendar-type').innerHTML=types.map(x=>`<option>${esc(x)}</option>`).join('')}
function updateObservation(){const student=cache.students.find(x=>x.id===$('#score-student').value);$('#score-observation').value=student?.observation||''}
function updateScoreValues(){const studentId=$('#score-student').value,subjectId=$('#score-subject').value,score=cache.scores.find(x=>String(x.student_id)===studentId&&String(x.subject_id)===subjectId),form=$('#score-form');for(const field of ['exam1','exam2','work','status']){const input=form.elements[field];if(input&&!input.disabled)input.value=score?.[field]??''}}
function openStudentDetails(studentId){const student=cache.students.find(x=>String(x.id)===String(studentId)),ranking=cache.ranking.find(x=>String(x.id)===String(studentId));if(!student)return;const scores=cache.scores.filter(x=>String(x.student_id)===String(studentId)).sort((a,b)=>a.subject.localeCompare(b.subject,'pt-BR')),content=$('#student-details-content');$('#student-details-title').textContent=student.name;content.innerHTML=`<div class="student-details-summary"><p><strong>${esc(student.rank)}</strong><span>Matrícula ${esc(student.id)}</span></p>${ranking?`<div><span>Colocação</span><strong>${ranking.position}º</strong></div><div><span>Pontos</span><strong>${fmt(ranking.points)} / ${fmt(ranking.distributed)}</strong></div><div><span>Média</span><strong>${fmt(ranking.average)}</strong></div>`:''}</div>${scores.length?`<div class="table-wrap"><table class="grade-table student-details-table"><thead><tr><th>Disciplina</th><th>AVC / 1º TAF</th><th>AVF / 2º TAF</th><th>Trabalho / 3º TAF</th><th>Total ou resultado</th></tr></thead><tbody>${scores.map(score=>{const apt=score.grading_mode==='apt',total=(score.exam1||0)+(score.exam2||0)+(score.work||0);return`<tr><td><strong>${esc(score.subject)}</strong></td><td>${apt||score.exam1==null?'—':fmt(score.exam1)}</td><td>${apt||score.exam2==null?'—':fmt(score.exam2)}</td><td>${apt||score.work==null?'—':fmt(score.work)}</td><td><strong>${apt?esc(score.status||'Não lançado'):fmt(total)}</strong></td></tr>`}).join('')}</tbody></table></div>`:'<div class="empty-student-scores"><strong>Nenhuma nota lançada</strong><p>Este discente ainda não possui matérias com pontos ou resultados cadastrados.</p></div>'}${student.observation?`<div class="student-observation"><strong>Observação</strong><p>${esc(student.observation)}</p></div>`:''}`;const dialog=$('#student-details-dialog');if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','')}
function closeStudentDetails(){const dialog=$('#student-details-dialog');if(typeof dialog.close==='function')dialog.close();else dialog.removeAttribute('open')}
function setScoreMode(mode){scoreMode=mode;document.querySelectorAll('.score-mode-button').forEach(button=>{const active=button.dataset.scoreMode===mode;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active))});const collective=mode==='collective';$('#score-form').hidden=collective;$('#collective-score-form').hidden=!collective;if(mode==='student'){$('#individual-score-title').textContent='Lançamento por discente';$('#individual-score-help').textContent='O discente permanecerá selecionado após salvar; escolha a próxima matéria.';$('#score-student').focus()}else if(mode==='subject'){$('#individual-score-title').textContent='Lançamento individual por matéria';$('#individual-score-help').textContent='A matéria permanecerá selecionada após salvar; escolha o próximo discente.';$('#score-subject').focus()}else{$('#collective-subject').focus();renderCollectiveScores()}}
function collectiveFields(subject){if(subject.grading_mode==='apt')return[{key:'status',label:'Resultado',type:'status'}];if(subject.grading_mode==='taf')return[{key:'exam1',label:'1º TAF',max:3},{key:'exam2',label:'2º TAF',max:3},{key:'work',label:'3º TAF',max:4}];if(subject.exam_count===1)return[{key:'exam2',label:'Avaliação Final (AVF)',max:7},{key:'work',label:'Trabalho',max:3}];return[{key:'exam1',label:'Avaliação Complementar (AVC)',max:3},{key:'exam2',label:'Avaliação Final (AVF)',max:4},{key:'work',label:'Trabalho',max:3}]}
function renderCollectiveScores(){const select=$('#collective-subject'),current=select.value;if(select.options.length<=1)select.innerHTML='<option value="">Selecione</option>'+cache.subjects.map(x=>`<option value="${x.id}">${esc(x.name)} — ${x.hours} h/a</option>`).join('');if(current)select.value=current;const subject=cache.subjects.find(x=>String(x.id)===select.value),container=$('#collective-score-table'),button=$('#collective-save-button');if(!subject){container.innerHTML='';button.disabled=true;$('#collective-rule').textContent='Selecione uma disciplina para montar a tabela.';return}const fields=collectiveFields(subject);$('#collective-rule').textContent=subject.grading_mode==='apt'?'Resultado qualitativo Apto/Inapto.':fields.map(x=>`${x.label}: ${x.max} pontos`).join(' • ');container.innerHTML=cache.students.length?`<div class="table-wrap"><table class="grade-table collective-table"><thead><tr><th>Discente</th>${fields.map(field=>`<th>${esc(field.label)}${field.max?`<small class="table-sub">Máx. ${field.max}</small>`:''}</th>`).join('')}</tr></thead><tbody>${cache.students.map(student=>{const score=cache.scores.find(x=>String(x.subject_id)===String(subject.id)&&String(x.student_id)===String(student.id))||{};return`<tr data-student-id="${esc(student.id)}"><td><strong>${esc(student.name)}</strong><small class="table-sub">${esc(student.id)} • ${esc(student.rank)}</small></td>${fields.map(field=>`<td>${field.type==='status'?`<select data-field="status"><option value="">Não lançado</option><option${score.status==='Apto'?' selected':''}>Apto</option><option${score.status==='Inapto'?' selected':''}>Inapto</option></select>`:`<input data-field="${field.key}" type="number" min="0" max="${field.max}" step="0.01" inputmode="decimal" value="${score[field.key]??''}" aria-label="${esc(field.label)} de ${esc(student.name)}">`}</td>`).join('')}</tr>`}).join('')}</tbody></table></div>`:'<p>Nenhum discente cadastrado.</p>';button.disabled=!cache.students.length}
document.querySelectorAll('.score-mode-button').forEach(button=>button.addEventListener('click',()=>setScoreMode(button.dataset.scoreMode)));
$('#score-subject').addEventListener('change',()=>{updateRule();updateScoreValues()});$('#score-student').addEventListener('change',()=>{updateObservation();updateScoreValues()});$('#calendar-subject').addEventListener('change',updateCalendarTypes);$('#collective-subject').addEventListener('change',renderCollectiveScores);
async function loadData(){const data=await api('/api/admin/data');cache=data;$('#score-student').innerHTML='<option value="">Selecione</option>'+data.students.map(x=>`<option value="${esc(x.id)}">${esc(x.name)} — ${esc(x.id)}</option>`).join('');const options=data.subjects.map(x=>`<option value="${x.id}">${esc(x.name)} — ${x.hours} h/a</option>`).join('');$('#score-subject').innerHTML='<option value="">Selecione</option>'+options;$('#calendar-subject').innerHTML=data.subjects.map(x=>`<option value="${esc(x.name)}">${esc(x.name)} — ${x.hours} h/a</option>`).join('');updateCalendarTypes();
$('#ranking-data').innerHTML=data.ranking.length?`<div class="table-wrap"><table class="grade-table"><thead><tr><th>Posição</th><th>Discente</th><th>Pontos obtidos</th><th>Pontos distribuídos</th><th>Média</th><th>Observação</th></tr></thead><tbody>${data.ranking.map(x=>`<tr><td><strong>${x.position}º</strong></td><td><button class="student-name-button" type="button" data-student-details="${esc(x.id)}" aria-label="Ver notas lançadas de ${esc(x.name)}">${esc(x.name)}</button><small class="table-sub">${esc(x.id)} • Clique no nome para consultar</small></td><td>${fmt(x.points)}</td><td>${fmt(x.distributed)}</td><td>${fmt(x.average)}</td><td>${esc(x.observation)||'—'}</td></tr>`).join('')}</tbody></table></div>`:'<p>Nenhum discente cadastrado.</p>';
$('#scores-data').innerHTML=data.scores.length?`<div class="table-wrap"><table class="grade-table"><thead><tr><th>Discente</th><th>Disciplina</th><th>Avaliação Complementar (AVC)</th><th>Avaliação Final (AVF)</th><th>Trabalho / 3º TAF</th><th>Total ou resultado</th></tr></thead><tbody>${data.scores.map(x=>`<tr><td>${esc(x.student_id)}</td><td>${esc(x.subject)}</td><td>${x.grading_mode==='apt'?'—':x.exam1==null?'—':fmt(x.exam1)}</td><td>${x.grading_mode==='apt'?'—':x.exam2==null?'—':fmt(x.exam2)}</td><td>${x.grading_mode==='apt'?'—':x.work==null?'—':fmt(x.work)}</td><td><strong>${x.grading_mode==='apt'?esc(x.status||'—'):fmt((x.exam1||0)+(x.exam2||0)+(x.work||0))}</strong></td></tr>`).join('')}</tbody></table></div>`:'<p>Nenhum resultado lançado.</p>'}
$('#refresh-button').addEventListener('click',loadData);$('#logout-button').addEventListener('click',async()=>{await api('/api/admin/logout',{method:'POST',body:'{}'});location.reload()});check();
document.addEventListener('click',event=>{const button=event.target.closest('[data-student-details]');if(button)openStudentDetails(button.dataset.studentDetails)});$('#student-details-close').addEventListener('click',closeStudentDetails);$('#student-details-close-bottom').addEventListener('click',closeStudentDetails);$('#student-details-dialog').addEventListener('click',event=>{if(event.target===$('#student-details-dialog'))closeStudentDetails()});
$('#pdf-report-button').addEventListener('click',async e=>{const button=e.currentTarget,message=$('#pdf-report-message');button.disabled=true;message.textContent='Gerando relatório...';try{const response=await fetch('/api/admin/report.pdf');if(!response.ok){const data=await response.json().catch(()=>({}));throw new Error(data.error||'Não foi possível gerar o relatório.')}const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`relatorio-notas-${new Date().toISOString().slice(0,10)}.pdf`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);message.textContent='Relatório gerado com sucesso.'}catch(error){message.textContent=error.message}finally{button.disabled=false}});
$('#calendar-import-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,file=$('#calendar-pdf').files[0],button=form.querySelector('button'),message=form.querySelector('.panel-message');if(!file)return;if(file.size>5*1024*1024){message.textContent='O PDF deve possuir no máximo 5 MB.';return}button.disabled=true;message.textContent='Lendo e validando o calendário...';try{const pdf_base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('Não foi possível ler o arquivo.'));reader.readAsDataURL(file)}),result=await api('/api/admin/calendar/import',{method:'POST',body:JSON.stringify({filename:file.name,pdf_base64})});message.textContent=`Calendário atualizado: ${result.imported} avaliações importadas.`;form.reset();await loadData()}catch(error){message.textContent=error.message}finally{button.disabled=false}});
$('#collective-score-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,button=$('#collective-save-button'),message=form.querySelector('.panel-message'),subject_id=$('#collective-subject').value,rows=[...$('#collective-score-table').querySelectorAll('tbody tr')],entries=rows.map(row=>{const entry={student_id:row.dataset.studentId};row.querySelectorAll('[data-field]').forEach(input=>entry[input.dataset.field]=input.value);return entry}),hasValues=entries.some(entry=>Object.entries(entry).some(([key,value])=>key!=='student_id'&&value!=='')),hasClears=entries.some(entry=>{const previous=cache.scores.find(score=>String(score.subject_id)===String(subject_id)&&String(score.student_id)===String(entry.student_id));if(!previous)return false;const empty=!Object.entries(entry).some(([key,value])=>key!=='student_id'&&value!=='');return empty});if(!hasValues&&!hasClears){message.textContent='Preencha pelo menos um resultado antes de salvar.';return}const payload=entries.filter(entry=>{const previous=cache.scores.find(score=>String(score.subject_id)===String(subject_id)&&String(score.student_id)===String(entry.student_id));const hasValue=Object.entries(entry).some(([key,value])=>key!=='student_id'&&value!=='');return hasValue||previous});button.disabled=true;message.textContent='Salvando lançamentos coletivos...';try{const result=await api('/api/admin/scores/bulk',{method:'POST',body:JSON.stringify({subject_id,entries:payload})});const cleared=Number(result.cleared||0);message.textContent=cleared?`${result.saved} salvos e ${cleared} limpos com sucesso.`:`${result.saved} resultados salvos com sucesso.`;await loadData();renderCollectiveScores()}catch(error){message.textContent=error.message}finally{button.disabled=false}});

// Mantém a lista de discentes da importação sincronizada com o cadastro principal.
new MutationObserver(()=>{const select=$('#pdf-score-student'),current=pdfImportStudentId||select.value;select.innerHTML=$('#score-student').innerHTML;select.value=current}).observe($('#score-student'),{childList:true});
function renderPdfScorePreview(entries){
  const container=$('#student-pdf-preview-table'),confirmButton=$('#student-pdf-confirm');
  confirmButton.disabled=false;confirmButton.textContent='Confirmar e salvar notas';$('#student-pdf-confirm-message').textContent='';
  container.innerHTML=`<div class="table-wrap"><table class="grade-table pdf-score-preview-table"><thead><tr><th>Importar</th><th>Disciplina</th><th>AVC / 1º TAF</th><th>AVF / 2º TAF</th><th>Trabalho / 3º TAF</th><th>Resultado</th></tr></thead><tbody>${entries.map(entry=>{
    const subject=cache.subjects.find(item=>String(item.id)===String(entry.subject_id));
    const previous=cache.scores.find(item=>String(item.student_id)===String(pdfImportStudentId)&&String(item.subject_id)===String(entry.subject_id));
    const apt=subject?.grading_mode==='apt',taf=subject?.grading_mode==='taf',single=subject?.exam_count===1&&subject?.grading_mode==='normal';
    const valueOf=(field)=>entry[field]??previous?.[field]??'';
    const scoreInput=(field,max,disabled=false)=>disabled?'—':`<input data-field="${field}" type="number" min="0" max="${max}" step="0.01" inputmode="decimal" value="${valueOf(field)}" aria-label="${field} de ${esc(entry.subject)}">`;
    return`<tr data-subject-id="${entry.subject_id}"><td><input class="pdf-import-check" type="checkbox" checked aria-label="Importar ${esc(entry.subject)}"></td><td><strong>${esc(entry.subject)}</strong><small class="table-sub">Campos vazios no PDF mantêm a nota já lançada</small></td><td>${apt?'—':scoreInput('exam1',3,single)}</td><td>${apt?'—':scoreInput('exam2',taf?3:single?7:4)}</td><td>${apt?'—':scoreInput('work',taf?4:3)}</td><td>${apt?`<select data-field="status" aria-label="Resultado de ${esc(entry.subject)}"><option value="">Selecione</option><option${valueOf('status')==='Apto'?' selected':''}>Apto</option><option${valueOf('status')==='Inapto'?' selected':''}>Inapto</option></select>`:'Pontuação'}</td></tr>`;
  }).join('')}</tbody></table></div>`;
  $('#student-pdf-preview').hidden=false;
}
async function analyzePdfImport(event){
  event.preventDefault();
  if(event.submitter?.id==='student-pdf-confirm')return confirmPdfImport(event);
  const form=$('#student-pdf-score-form'),file=$('#student-score-pdf').files[0],student_id=$('#pdf-score-student').value;
  const button=$('#student-pdf-analyze-button'),message=form.querySelector('.panel-message');
  if(!student_id){message.textContent='Selecione o discente antes de importar o PDF.';$('#pdf-score-student').focus();showAdminFeedback({title:'Falta escolher o discente',eyebrow:'Atenção',message:'Selecione o discente antes de ler o PDF.',userAction:'Escolha o nome na lista e tente novamente.',tone:'warning'});return}
  if(!file){message.textContent='Selecione o arquivo PDF de notas.';$('#student-score-pdf').focus();showAdminFeedback({title:'Falta o arquivo PDF',eyebrow:'Atenção',message:'Selecione o arquivo PDF com as notas.',userAction:'Clique em escolher arquivo, selecione o PDF e tente novamente.',tone:'warning'});return}
  if(file.type&&file.type!=='application/pdf'&&!file.name.toLowerCase().endsWith('.pdf')){message.textContent='O arquivo selecionado precisa estar no formato PDF.';showAdminFeedback({title:'Arquivo inválido',eyebrow:'Atenção',message:'O arquivo precisa ser um PDF.',userAction:'Salve ou exporte o documento em PDF e envie novamente.',tone:'warning'});return}
  if(file.size>5*1024*1024){message.textContent='O PDF deve possuir no máximo 5 MB.';showAdminFeedback({title:'Arquivo muito grande',eyebrow:'Atenção',message:'O PDF ultrapassa o limite de 5 MB.',userAction:'Reduza o tamanho do arquivo ou divida o conteúdo e tente de novo.',tone:'warning'});return}
  $('#student-pdf-preview').hidden=true;$('#student-pdf-confirm-message').textContent='';
  button.disabled=true;button.textContent='Lendo o PDF...';message.textContent='Lendo as disciplinas e notas do PDF. Elas serão vinculadas ao discente selecionado. Aguarde...';
  try{
    const pdf_base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=()=>reject(new Error('Não foi possível ler o arquivo.'));reader.readAsDataURL(file)});
    const result=await api('/api/admin/student-scores/import',{method:'POST',body:JSON.stringify({action:'preview',student_id,pdf_base64})});
    pdfImportStudentId=student_id;renderPdfScorePreview(result.entries);
    message.textContent=`${result.entries.length} disciplina(s) reconhecida(s) para ${result.student.name} (matrícula ${student_id}). Confira a prévia antes de confirmar.`;
    if(result.user_action||(result.logs||[]).some(item=>String(item.level).toLowerCase()==='warning')){
      showAdminFeedback({title:'Prévia pronta, com avisos',eyebrow:'Conferência',message:`Foram reconhecidas ${result.entries.length} disciplina(s). Revise a prévia antes de salvar.`,userAction:result.user_action||'',logs:result.logs||[],tone:'warning'});
    }
    $('#student-pdf-preview').scrollIntoView({behavior:'smooth',block:'start'});
  }catch(error){
    message.textContent=error.message||'Não foi possível importar o PDF.';$('#student-pdf-preview').hidden=true;
    showAdminFeedback({title:'Não foi possível ler o PDF',eyebrow:'Erro na importação',message:error.message||'Não foi possível importar o PDF.',userAction:error.userAction||'Confira o arquivo e o discente selecionado, depois tente novamente.',logs:error.logs||[{level:'error',message:error.message||'Falha na leitura do PDF.'}],tone:'error'});
  }finally{
    button.disabled=false;button.textContent='Ler PDF e conferir notas';
  }
}
$('#student-pdf-score-form').addEventListener('submit',analyzePdfImport);
$('#pdf-score-student').addEventListener('change',()=>{pdfImportStudentId='';$('#student-pdf-preview').hidden=true;$('#student-pdf-preview-table').innerHTML=''});
$('#student-score-pdf').addEventListener('change',()=>{$('#student-pdf-preview').hidden=true;$('#student-pdf-preview-table').innerHTML=''});
$('#student-pdf-cancel').addEventListener('click',()=>{$('#student-pdf-preview').hidden=true;$('#student-pdf-preview-table').innerHTML='';$('#student-pdf-confirm-message').textContent=''});
async function confirmPdfImport(event){
  event.preventDefault();
  event.stopPropagation();
  const button=$('#student-pdf-confirm'),message=$('#student-pdf-confirm-message'),formMessage=$('#student-pdf-score-form .panel-message');
  if(button.dataset.saving==='true')return;
  const student_id=pdfImportStudentId||$('#pdf-score-student').value;
  const entries=[...$('#student-pdf-preview-table tbody tr')]
    .filter(row=>row.querySelector('.pdf-import-check')?.checked)
    .map(row=>{const entry={subject_id:row.dataset.subjectId};row.querySelectorAll('[data-field]').forEach(input=>entry[input.dataset.field]=input.value);return entry});
  if(!student_id){message.textContent='Selecione novamente o discente antes de salvar.';showAdminFeedback({title:'Discente não identificado',eyebrow:'Atenção',message:'Não foi possível identificar o discente desta importação.',userAction:'Selecione o discente, leia o PDF outra vez e confirme o salvamento.',tone:'warning'});return}
  if(!entries.length){message.textContent='Selecione pelo menos uma matéria para importar.';showAdminFeedback({title:'Nenhuma matéria marcada',eyebrow:'Atenção',message:'Marque pelo menos uma disciplina na prévia para salvar.',userAction:'Marque as caixas das matérias desejadas e clique novamente em salvar.',tone:'warning'});return}
  button.dataset.saving='true';button.disabled=true;button.textContent='Salvando...';message.textContent='Enviando e conferindo as notas no banco de dados...';
  try{
    const student=cache.students.find(item=>String(item.id)===String(student_id));
    let saved=0;
    for(const entry of entries){
      await api('/api/admin/score',{
        method:'POST',
        body:JSON.stringify({
          student_id,
          ...entry,
          observation:student?.observation||''
        })
      });
      saved+=1;
      message.textContent=`Salvando notas... ${saved} de ${entries.length} disciplina(s).`;
    }
    const success=`${saved} disciplina(s) salva(s) pela mesma rotina do lançamento manual.`;
    message.textContent=success;formMessage.textContent=`Notas salvas para o discente selecionado. ${success}`;
    button.textContent='Importação concluída';pdfImportStudentId=student_id;
    $('#student-score-pdf').value='';
    try{await loadData();$('#pdf-score-student').value=student_id}
    catch{formMessage.textContent=`${success} A tela não conseguiu atualizar automaticamente; clique em Atualizar para conferir.`}
    $('#student-pdf-preview').scrollIntoView({behavior:'smooth',block:'center'});
  }catch(error){
    const detail=error.message==='Rota inexistente.'?'O servidor ainda não possui a atualização da importação por PDF. Atualize também o backend no Render.':(error.message||'Não foi possível salvar as notas.');
    const userAction=error.userAction||(error.message==='Rota inexistente.'?'Peça para publicar o painel e o servidor juntos e depois atualize a página com Ctrl+F5.':'Confira os detalhes abaixo, corrija o que for necessário e tente salvar novamente.');
    message.textContent=detail;formMessage.textContent=detail;button.textContent='Tentar salvar novamente';
    showAdminFeedback({title:'As notas não foram confirmadas',eyebrow:'Erro ao salvar',message:detail,userAction,logs:error.logs||[{level:'error',message:detail}],tone:'error'});
  }finally{
    button.dataset.saving='false';button.disabled=false;
  }
}
// O botão existe desde o carregamento da página; o vínculo direto garante o clique.
